name: CICD

on:
  push:
    branches:
      - main

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        run: echo "Docker container build"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the app
        run: echo "Docker Compose deployed the app"
